# `sheldon` configuration file
# ----------------------------
#
# You can modify this file directly or you can use one of the following
# `sheldon` commands which are provided to assist in editing the config file:
#
# - `sheldon add` to add a new plugin to the config file
# - `sheldon edit` to open up the config file in the default editor
# - `sheldon remove` to remove a plugin from the config file
#
# See the documentation for more https://github.com/rossmacarthur/sheldon#readme

shell = "zsh"

[templates]
bin_path = 'export PATH="{{dir }}/bin:$PATH"'
source_zcolors = "source $HOME/.cache/zcolors"

[plugins]

[plugins.auto-notify]
github = "MichaelAquilina/zsh-auto-notify"

#[plugins.extend-history]
#github = "xav-b/zsh-extend-history"

[plugins.forgit]
github = "wfxr/forgit"

[plugins.alias-tips]
github = 'djui/alias-tips'

[plugins.up-dir]
github = 'sgpthomas/zsh-up-dir'

[plugins.fzf]
github = "unixorn/fzf-zsh-plugin"
#apply = ["bin_path", "source"]

[plugins.fzf-tab]
github = "Aloxaf/fzf-tab"

[plugins.syntax-highlighting]
github = "zsh-users/zsh-syntax-highlighting"

[plugins.autosuggestions]
github = "zsh-users/zsh-autosuggestions"

