syntax on

set tabstop=2
set softtabstop=2
set shiftwidth=2
set expandtab

""" minpac begin """
" Normally this if-block is not needed, because `:set nocp` is done
" automatically when .vimrc is found. However, this might be useful
" when you execute `vim -u .vimrc` from the command line.
if &compatible
  " `:set nocp` has many side effects. Therefore this should be done
  " only when 'compatible' is set.
  set nocompatible
endif

set packpath^=~/.vim
packadd minpac

call minpac#init()

" minpac must have {'type': 'opt'} so that it can be loaded with `packadd`.
call minpac#add('k-takata/minpac', {'type': 'opt'})

" Add other plugins here.
call minpac#add('rodjek/vim-puppet')
call minpac#add('fatih/vim-go')


" Load the plugins right now. (optional)
packloadall

""" minpac end """

