theme = "bad-wolf"
icons = "awesome5"

[[block]]
block = "cpu"
interval = 1
format = "{utilization} @ {frequency}"

[[block]]
block = "load"
interval = 4
format = "{1m}"

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{Mup}%"
format_swap = "{SUp}%"

[[block]]
block = "disk_space"
path = "/"
alias = "/"
info_type = "available"
unit = "GB"
interval = 20
warning = 20.0
alert = 10.0

[[block]]
block = "networkmanager"
ap_format = "{strength}% {ssid}"
device_format = "{icon} {ap}"
interface_name_exclude = ["br\\-[0-9a-f]{12}", "docker\\d+"]
interface_name_include = []

[[block]]
block = "battery"
interval = 10
format = "{percentage}% {time} - {power}W"
full_format = "{percentage}%"

[[block]]
block = "backlight"

# MX Master
[[block]]
block = "bluetooth"
mac = "FF:FD:82:FE:A3:5C"
hide_disconnected = true

# B&O H7
[[block]]
block = "bluetooth"
mac = "00:09:A7:0D:82:2C"
hide_disconnected = true

[[block]]
block = "sound"

[[block]]
block = "time"
interval = 60
format = "%a %d/%m %R"

