[theme]
#theme = "bad-wolf"
theme = "dracula"

[icons]
icons = "awesome6"

[[block]]
block = "cpu"
interval = 2
format = " $icon $utilization @ $frequency "

[[block]]
block = "load"
interval = 4
format = " $icon $1m.eng(w:4)"

[[block]]
block = "memory"
format = " $icon$mem_used.eng(prefix:M)/$mem_total ($mem_used_percents)"
format_alt = "$icon_swap $swap_used.eng(prefix:M)/$swap_total.eng(w:1) ($swap_used_percents.eng(w:1))"

[[block]]
block = "disk_space"
path = "/"
info_type = "available"
alert_unit = "GB"

[[block]]
block = "net"
format = " $icon {$signal_strength $ssid.str(max_w:12)|Wired} "

[[block]]
block = "battery"
device = "BAT0"
interval = 10
format = " $icon $percentage $time $power "
full_format = "$percentage"

[[block]]
block = "backlight"

[[block]]
block = "hueshift"
hue_shifter = "redshift"
step = 100
click_temp = 3500

# MX Master
[[block]]
block = "bluetooth"
mac = "FF:FD:82:FE:A3:5C"
disconnected_format = ""

# B&O H7
[[block]]
block = "bluetooth"
mac = "00:09:A7:0D:82:2C"
disconnected_format = ""

[[block]]
block = "sound"
format = " $icon {$volume.eng(w:2)|} $output_description.str(max_w:12)"
max_vol = 100
show_volume_when_muted = true

[[block]]
block = "pomodoro"
notify_cmd = "notify-send -u critical -w '{msg}'"
blocking_cmd = true

[[block]]
block = "notify"
driver = "dunst"
format = " $icon {$paused{Off}|On} {($notification_count.eng(w:1)) |} "

[[block]]
block = "time"
interval = 1
format = " $icon $timestamp.datetime(f:'%a %d/%m %T') "

